export const API_SERIES_GET_SERIES_MODEL = 'API_SERIES_GET_SERIES_MODEL';
export const API_SERIES_GET_SERIES_PAGE = 'API_SERIES_GET_SERIES_PAGE';
export const API_SERIES_GET_SERIES_CHARACTERS = 'API_SERIES_GET_SERIES_CHARACTERS';
export const API_SERIES_GET_SERIES_STAFF = 'API_SERIES_GET_SERIES_STAFF';
export const API_SERIES_GET_SERIES_ACTORS = 'API_SERIES_GET_SERIES_ACTORS';
export const API_SERIES_BROWSE_SERIES = 'API_SERIES_BROWSE_SERIES';
export const API_SERIES_GET_GENRE_LIST = 'API_SERIES_GET_GENRE_LIST';
